// Generated by CoffeeScript 1.10.0
(function() {
  var funcname, types;

  types = require('types.js');

  funcname = function(func) {
    var extract;
    if (types.notFunction(func)) {
      return funcname.log('func-name: error, cannot get function name from a non-function argument!');
    }
    if ((types.isString(func.name)) && func.name.length) {
      return func.name;
    }
    extract = types.forceArray(/^\s*function\s*([^\(]*)/im.exec(func.toString()));
    if ((extract.length > 1) && (types.isString(extract[1])) && extract[1].length) {
      return extract[1];
    }
    return types.forceString(funcname.anonymusName);
  };

  funcname.anonymusName = '';

  funcname.nameAnonymus = function(name) {
    funcname.anonymusName = types.forceString(name, 'anonymus');
    return funcname;
  };

  funcname.log = types.forceFunction();

  funcname.debug = function(handler) {
    funcname.log = types.forceFunction(handler, console.log);
    return funcname;
  };

  module.exports = funcname;

}).call(this);
