// Generated by CoffeeScript 1.10.0
(function() {
  var funcname, types;

  types = require('types.js');

  funcname = function(func) {
    var extract, name;
    name = types.forceString(funcname.anonymusName);
    if (types.isFunction(func)) {
      if ((types.isString(func.name)) && func.name.length) {
        return func.name;
      }
      extract = types.forceArray(/^\s*function\s*([^\(]*)/im.exec(func.toString()));
      if (extract.length && extract[1]) {
        return types.forceString(extract[1], name);
      }
    }
    return name;
  };

  funcname.anonymusName = '';

  funcname.nameAnonymus = function(name) {
    funcname.anonymusName = types.forceString(name, 'anonymus');
    return funcname;
  };

  module.exports = funcname;

}).call(this);
